openstack-python-clients: add `osc-lib` package
The openstack client tool fails due to the missing `osc_lib`
python module, making the openstack-cli unusable:

$ openstack user list
Traceback (most recent call last):
  File "/usr/bin/openstack", line 6, in <module>
    from openstackclient.shell import main
  File "/usr/lib/python2.7/site-packages/openstackclient/shell.py", line
22, in <module>
    from osc_lib.api import auth
ImportError: No module named osc_lib.api

this commit fixes this issue by adding the missing python module

Signed-off-by: Simental Magana, Marcos <marcos.simental.magana@intel.com>